export const CLEAR_FIREBASE = 'CLEAR_FIREBASE';

export const CHANGE_ROUTE = 'CHANGE_ROUTE';

export const REQUEST_CREATE_ACCOUNT = 'REQUEST_CREATE_ACCOUNT';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE';

export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const REQUEST_VERIFY_USER = 'REQUEST_VERIFY_USER';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const VERIFY_USER_NOONE_LOGGED_IN = 'VERIFY_USER_NOONE_LOGGED_IN';

export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_ERROR = 'GET_ITEMS_ERROR';

export const OPEN_LOGIN = 'OPEN_LOGIN';

export const REQUEST_ADD_ITEM = 'REQUEST_ADD_ITEM';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const REQUEST_UPDATE_USER = 'REQUEST_UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
